services:

  db:
    image: 'postgres:16.2'
    container_name: service-auth-db
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: service-auth
      POSTGRES_USER: service-auth-owner
      POSTGRES_PASSWORD: service-auth-owner
